name: Pull Requests

on:
  pull_request:
    branches: []

  push:
    branches: []

permissions:
  pull-requests: write

jobs:
  uneditable:
    uses: laravel/.github/.github/workflows/pull-requests.yml@main
